feat: chips component
Informasjonsforvaltning/catalog-frontend pull request #128
Opened 2023-06-09 11:00 UTC by hegeaal

2023-06-19 06:23 UTC, jeffreiffers commented
Du kan vel erstatte denne med den som ligger i designsystemet?

2023-06-19 06:25 UTC, jeffreiffers approved these changes

2023-06-19 07:13 UTC, terjesyl requested changes

2023-06-19 07:13 UTC, terjesyl commented on apps/concept-catalog/pages/[catalogId]/index.tsx
> +                    title='a11y-title'
Legg til `title` (eller tom hvis dekorativt ikon)

2023-06-19 07:13 UTC, terjesyl commented on apps/concept-catalog/pages/[catalogId]/index.tsx
> +                    title='a11y-title'
samme her

2023-06-19 07:13 UTC, terjesyl commented on libs/ui/src/lib/chips/removable.tsx
> +        aria-label={`${children}`}
Vises children (string) som synlig tekst på knappen også? Da skal man ikke bruke aria-label.

2023-06-19 10:25 UTC, hegeaal commented on libs/ui/src/lib/chips/removable.tsx
> +        aria-label={`${children}`}
Dette er egentlig ikke min kode, tipper det bare er blått pga. formatering 😅 Så jeg vet ikke helt, men kan ta en titt..

2023-06-20 13:03 UTC, terjesyl approved these changes

2023-06-21 06:32 UTC, merged