feat(concept): add suggestions page
Informasjonsforvaltning/catalog-frontend pull request #196
Opened 2023-06-22 12:30 UTC by pooriamehregan

solves https://github.com/Informasjonsforvaltning/catalog-frontend/issues/168
solves https://github.com/Informasjonsforvaltning/catalog-frontend/issues/170
solves https://github.com/Informasjonsforvaltning/catalog-frontend/issues/172

2023-06-26 12:13 UTC, jeffreiffers commented on apps/concept-catalog/pages/[catalogId]/suggestions/index.tsx
> +    router.push(`/catalog/${router.query.catalogId}/suggestions/${e.target.attributes.itemID.value}`);
valider input til urlen (de finner eksempler i repoet)

2023-06-26 12:18 UTC, jeffreiffers requested changes

2023-06-26 12:18 UTC, jeffreiffers commented on apps/concept-catalog/pages/[catalogId]/suggestions/index.tsx
> +      notFound: true,
Denne logikker har blitt endret. Sjekk https://github.com/Informasjonsforvaltning/catalog-frontend/pull/198

2023-06-26 12:18 UTC, jeffreiffers commented on apps/concept-catalog/pages/[catalogId]/suggestions/index.tsx
> +            <ListItem itemID='1'>Begrep 1</ListItem>
Bør det kommer frem i saken at dette er skjelettet til endingsforslagoversikten?

2023-06-28 09:25 UTC, pooriamehregan commented on apps/concept-catalog/pages/[catalogId]/suggestions/index.tsx
> +            <ListItem itemID='1'>Begrep 1</ListItem>
Godt poeng! Det står om det i saken:
https://github.com/Informasjonsforvaltning/catalog-frontend/issues/172

2023-06-28 10:21 UTC, pooriamehregan commented on apps/concept-catalog/pages/[catalogId]/suggestions/index.tsx
> +            <ListItem itemID='1'>Begrep 1</ListItem>
lagde ny issue på det https://github.com/Informasjonsforvaltning/catalog-frontend/issues/203

2023-06-30 09:57 UTC, jeffreiffers approved these changes

2023-06-30 10:02 UTC, merged