Feat/ts/form for new concept suggestions
Informasjonsforvaltning/catalog-frontend pull request #252
Opened 2023-08-17 12:57 UTC by terjesyl

2023-08-22 10:03 UTC, terjesyl commented
Knyttet til: https://github.com/Informasjonsforvaltning/catalog-frontend/issues/173

2023-08-28 06:42 UTC, pooriamehregan requested changes

2023-08-28 06:42 UTC, pooriamehregan commented on apps/concept-catalog/pages/[catalogId]/change-requests/[id]/index.tsx
> +    console.log(`Submitting form. Values: ${JSON.stringify(values)}`);
```suggestion
```

2023-08-28 06:42 UTC, pooriamehregan commented on apps/concept-catalog/pages/[catalogId]/change-requests/[id]/index.tsx
> +      console.log('Submitted!');
```suggestion
```

2023-10-05 10:21 UTC, pooriamehregan approved these changes

2023-10-05 10:21 UTC, pooriamehregan commented on apps/concept-catalog/components/change-request-form/change-request-form.tsx
> +                            {values?.folkeligForklaring?.kildebeskrivelse?.kilde?.map((_, index) => (
kanskje lurt å ikke bruke index som key

2023-10-05 10:21 UTC, pooriamehregan commented on apps/concept-catalog/components/form-field-container/form-field-container.module.css
> +
```suggestion

```

2023-10-05 10:21 UTC, pooriamehregan commented on apps/concept-catalog/components/form-field-container/form-field-container.module.css
> +
```suggestion

```

2023-10-05 10:21 UTC, pooriamehregan commented on apps/concept-catalog/components/form-field-container/form-field-container.module.css
> +
```suggestion

```

2023-10-05 10:21 UTC, pooriamehregan commented on apps/concept-catalog/pages/[catalogId]/change-requests/[changeRequestId]/edit.tsx
> +  //   });
```suggestion

```

2023-10-05 11:36 UTC, terjesyl commented on apps/concept-catalog/components/form-field-container/form-field-container.module.css
> +
Prettier insisterer på linjeskift ❓

2023-10-09 06:13 UTC, merged