Feat/ha/replace chip with design system chip
Informasjonsforvaltning/catalog-frontend pull request #268
Opened 2023-08-30 07:40 UTC by hegeaal

2023-08-30 10:54 UTC, NilsOveTen commented on apps/concept-catalog/context/search/state.ts
> +export type FilterTypes = 'published' | 'status' | 'assignedUser' | 'subject';
Blir dette brukt?

2023-08-30 10:54 UTC, NilsOveTen commented on apps/concept-catalog/context/search/state.ts
> +  filters: {
Trenger ikke defaultState for internalFields?

2023-08-30 10:54 UTC, NilsOveTen commented on apps/concept-catalog/pages/[catalogId]/index.tsx
> +        break;
Det skal ikke være mulig å fjerne internalFields-filtrering?

2023-08-30 10:54 UTC, NilsOveTen commented on apps/concept-catalog/pages/[catalogId]/index.tsx
> +              <div className={styles.chips}>
internalFields?

2023-08-31 06:26 UTC, jeffreiffers approved these changes

2023-08-31 06:26 UTC, jeffreiffers commented on apps/concept-catalog/pages/[catalogId]/index.tsx
> +  const removeFilter = (filterName, filterType: string) => {
```suggestion
  const removeFilter = (filterName, filterType: FilterType) => {
```

2023-08-31 06:28 UTC, jeffreiffers requested changes

2023-08-31 06:28 UTC, jeffreiffers commented on apps/concept-catalog/context/search/state.ts
> +export type FilterTypes = 'published' | 'status' | 'assignedUser' | 'subject';
```suggestion
export type FilterType = 'published' | 'status' | 'assignedUser' | 'subject';
```

2023-08-31 06:29 UTC, jeffreiffers commented on apps/concept-catalog/context/search/state.ts
> +export type FilterTypes = 'published' | 'status' | 'assignedUser' | 'subject';
Sjekk mitt forslag

2023-09-01 08:40 UTC, pooriamehregan approved these changes

2023-09-04 05:53 UTC, NilsOveTen commented on apps/catalog-admin/components/code-list-editor/index.tsx
> +        ?.filter((code: Code) => code.id !== currentCode?.id && code.parentID !== currentCode.id)
Er det ikke bedre å starte med nullsjekk for currentCode, og returnere tom liste hvis den ikke er satt?

Det virker på som at potensialet for at currentCode ikke har verdi gjør filteret noe uoversiktelig

2023-09-04 11:17 UTC, jeffreiffers approved these changes

2023-09-04 13:30 UTC, merged