Feat/ts/add language indicator
Informasjonsforvaltning/catalog-frontend pull request #269
Opened 2023-08-31 08:41 UTC by terjesyl

2023-08-31 10:26 UTC, terjesyl commented
Er det bedre å bruke `export type Languages = 'nb' | 'nn' | 'no' | 'en';` for å kunne passe string-verdier, i stedet for å skrive `LanguageCodes.nb` eller `LanguageCodes['nb']` osv.?

2023-08-31 13:16 UTC, jeffreiffers requested changes

2023-08-31 13:16 UTC, jeffreiffers commented on libs/ui/src/lib/language-indicator/language-indicator.module.css
> +.containerInformationmodel {
Tror at vi går vekk fra å bruke forskjellige farger for de ulike typene i nye designet. Hør med Matheus men tror vi skal bort fra det.

2023-09-01 06:28 UTC, pooriamehregan approved these changes

2023-09-04 08:13 UTC, pooriamehregan approved these changes

2023-09-05 06:49 UTC, jeffreiffers approved these changes

2023-09-05 07:43 UTC, merged