Fix/ha/bugs catalog admin
Informasjonsforvaltning/catalog-frontend pull request #329
Opened 2023-09-28 13:41 UTC by hegeaal

2023-09-29 07:33 UTC, jeffreiffers requested changes

2023-09-29 07:33 UTC, jeffreiffers commented on apps/catalog-admin/pages/catalogs/[catalogId]/index.tsx
> +import styles from '../../shared-style.module.css';
Ikke importer som module men globalt

2023-09-29 07:33 UTC, jeffreiffers commented on apps/catalog-admin/pages/catalogs/[catalogId]/index.tsx
> +import styles from '../../shared-style.module.css';
import '../../global.css'

2023-10-02 16:54 UTC, NilsOveTen approved these changes

2023-10-09 08:51 UTC, terjesyl commented
@jeffreiffers @hegeaal Var denne klar til å merges?

2023-10-10 06:27 UTC, jeffreiffers approved these changes

2023-10-10 06:44 UTC, merged