Fix/small bugs admin
Informasjonsforvaltning/catalog-frontend pull request #332
Opened 2023-10-01 09:59 UTC by hegeaal

2023-10-11 07:46 UTC, jeffreiffers requested changes

2023-10-11 07:46 UTC, jeffreiffers commented on apps/catalog-admin/components/codes-editor/codes-editor.module.css
> +  height: 506px;
Ønsker vi en fast høyde i piksler?

2023-10-11 07:46 UTC, jeffreiffers commented on apps/catalog-admin/components/codes-editor/index.tsx
> +    const convertedValue = value !== null ? +value : null;
```suggestion
    const valueAsNumber = value !== null ? +value : null;
```

2023-10-11 13:13 UTC, NilsOveTen approved these changes

2023-10-12 10:12 UTC, jeffreiffers approved these changes

2023-10-12 12:36 UTC, merged