fix (concept): import type check and error handling
Informasjonsforvaltning/catalog-frontend pull request #401
Opened 2023-11-07 06:40 UTC by jeffreiffers

2023-11-07 07:33 UTC, NilsOveTen commented
Skulle vi ikke avvente all endring av catalog-frontend til @pooriamehregan får merga #391

2023-11-13 13:40 UTC, pooriamehregan requested changes

2023-11-13 13:40 UTC, pooriamehregan commented on apps/concept-catalog/app/api/concepts/[slug]/route.ts
> +      return new Response(JSON.stringify(await response.json()), { status: response.status });
```suggestion
      const jsonResponse = await response.json();
      return new Response(JSON.stringify(jsonResponse), { status: response.status });
```

2023-11-13 13:40 UTC, pooriamehregan commented on apps/concept-catalog/hooks/import.ts
> +          return Promise.reject((await response.json()).message);
```suggestion
          const jsonResponse = await response.json();
          return Promise.reject(jsonResponse.message);
```

2023-11-13 13:40 UTC, pooriamehregan commented on apps/concept-catalog/hooks/import.ts
> +        return Promise.resolve(await response.json());
```suggestion
        const jsonResponse = await response.json();
        return Promise.resolve(jsonResponse);
```

2023-11-14 09:18 UTC, hegeaal approved these changes

2023-11-14 15:54 UTC, merged