fix: testing
Informasjonsforvaltning/catalog-frontend pull request #429
Opened 2023-11-23 15:12 UTC by pooriamehregan

fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/427

2023-11-27 06:52 UTC, NilsOveTen commented on apps/concept-catalog/app/page.tsx
> +  const orgNumber = getOrganizationNumber(`${session?.accessToken}`);
Hva skjer for folk som har tilgang til flere organisasjoner?
Hva med sys-admin?

2023-11-27 09:28 UTC, jeffreiffers requested changes

2023-11-27 09:28 UTC, jeffreiffers commented on apps/catalog-admin/app/page.tsx
> +    redirect(`/auth/signin`);
Sett callbackUrl til FDK_REGISTRATION_BASE_URI

2023-12-05 08:16 UTC, jeffreiffers commented
Denne er løst av https://github.com/Informasjonsforvaltning/catalog-frontend/pull/461

2023-12-05 08:16 UTC, closed without merging