refactor(concept:changeRequest): edit page and new concept suggestion page
Informasjonsforvaltning/catalog-frontend pull request #471
Opened 2023-12-11 09:18 UTC by terjesyl

* edit ChangeRequest types

* stringify request body in API

* make a separate banner component

2023-12-11 14:40 UTC, jeffreiffers approved these changes

2023-12-11 14:40 UTC, jeffreiffers commented on apps/concept-catalog/app/[catalogId]/change-requests/new/new-concept-suggestion-client.tsx
> +interface Props {
Kanskje lage felles props. Ser at den er likt flere steder.

2023-12-13 10:15 UTC, NilsOveTen requested changes
Er fortsatt id-krøll her

2023-12-14 09:07 UTC, NilsOveTen approved these changes

2023-12-14 09:36 UTC, merged