Feat/ha/dataset catalog setup
Informasjonsforvaltning/catalog-frontend pull request #730
Opened 2024-08-08 11:19 UTC by hegeaal

2024-08-09 13:25 UTC, NilsOveTen requested changes

2024-08-09 13:25 UTC, NilsOveTen commented on deploy/demo/dataset-catalog-frontend/kustomization.yaml
> +---
demo er litt for forskjellig fra staging og prod
- mangler env
- mangler ingress
- bruker ikke base

2024-08-12 11:51 UTC, terjesyl commented on apps/dataset-catalog/Dockerfile
> +CMD yarn next start -p 8080
Skriv om på format

`CMD ["yarn" "next" "start" "-p" "8080"]`

eller eksplisitt angi SHELL:
```
FROM alpine
RUN apk add bash
SHELL ["/bin/bash", "-c"]
ENTRYPOINT echo "hello world"
```
ref: https://docs.docker.com/go/dockerfile/rule/json-args-recommended/

2024-08-12 12:01 UTC, NilsOveTen commented on deploy/demo/dataset-catalog-frontend/dataset-catalog-frontend-env.yaml
> +              value: https://datasettkatalog.fellesdatakatalog.digdir.no
```suggestion
              value: https://datasettkatalog.demo.fellesdatakatalog.digdir.no
```

2024-08-12 12:01 UTC, NilsOveTen commented on deploy/demo/dataset-catalog-frontend/dataset-catalog-frontend-ingress.yaml
> +    - host: datasettkatalog.fellesdatakatalog.digdir.no
```suggestion
    - host: datasettkatalog.demo.fellesdatakatalog.digdir.no
```

2024-08-12 12:02 UTC, NilsOveTen commented on apps/dataset-catalog/Dockerfile
> +CMD yarn next start -p 8080
ta det i så fall en egen refaktorerings-pr som fikser alle dockerfilene samtidig

2024-08-13 11:38 UTC, hegeaal commented on apps/dataset-catalog/Dockerfile
> +CMD yarn next start -p 8080
Kan ta dette i egen PR

2024-08-13 12:10 UTC, merged