Feat/ha/codelists page
Informasjonsforvaltning/catalog-frontend pull request #87
Opened 2023-05-30 10:32 UTC by hegeaal

Statisk side for codelists. https://catalog-admin.staging.fellesdatakatalog.digdir.no/catalogs/910244132/concepts/code-lists 

closes #81

2023-05-31 11:40 UTC, terjesyl requested changes

2023-05-31 11:40 UTC, terjesyl commented on apps/catalog-admin/pages/catalogs/[catalogId]/concepts/code-lists/index.tsx
> +            ariaLabel={''}
Bør denne være tom streng? Har du testet med skjermleser at den fungerer som forventet og leser opp riktig tekst?

2023-05-31 11:40 UTC, terjesyl commented on apps/catalog-admin/pages/catalogs/[catalogId]/concepts/code-lists/index.tsx
> +                icon={<PlusCircleIcon title='a11y-title' />}
Ville undersøkt om `title` skal ha tekst her. Kan være at Button-teksten er forklarende nok, og at PlusCircleIcon ikke trenger title. Hvis PlusCircleIcon fungerer som et forklarende symbol og ikke bare er dekorativ, bør `title` beskrive funksjonaliteten.

2023-05-31 11:40 UTC, terjesyl commented on apps/catalog-admin/pages/catalogs/[catalogId]/concepts/code-lists/index.tsx
> +              icon={<FileImportIcon title='a11y-title' />}
Samme her for `title` som over

2023-05-31 14:38 UTC, hegeaal commented on apps/catalog-admin/pages/catalogs/[catalogId]/concepts/code-lists/index.tsx
> +            ariaLabel={''}
Wops nei, glemte å fylle inn 😅

2023-06-05 08:36 UTC, terjesyl approved these changes

2023-06-06 05:35 UTC, NilsOveTen approved these changes

2023-06-06 06:54 UTC, merged