feat: image uploader component
Informasjonsforvaltning/catalog-frontend pull request #98
Opened 2023-06-02 13:04 UTC by hegeaal

2023-06-06 10:14 UTC, jeffreiffers requested changes

2023-06-08 09:28 UTC, pooriamehregan approved these changes

2023-06-09 13:26 UTC, jeffreiffers requested changes

2023-06-09 13:26 UTC, jeffreiffers commented on apps/catalog-admin/components/banner/index.tsx
> +          src={logo}
legg til en sjekk om urlen er riktig

2023-06-09 13:26 UTC, jeffreiffers commented on apps/catalog-admin/components/image-uploader/index.tsx
> +        <label
Har har laget en UploadButton i ui som ligger i import branchen.

2023-06-13 13:11 UTC, jeffreiffers approved these changes

2023-06-13 13:44 UTC, merged